window.TAMO_ON_PARTNERS_CONFIG = Object.freeze({
  appName: "Tâmo On Partners Preview",
  version: "0.1.21",
  environment: "partners_preview",
  realMoney: false,
  payments: {
    routingEnabled: true,
    defaultMethod: "pix_direct_partner",
    bankPix: {
      enabled: true,
      networkEnabled: false,
      webhookBasePath: "/api/webhooks/pix",
      supportedAdapters: ["SICOOB", "SICREDI", "BB", "INTER", "GENERIC_MANUAL"]
    }
  },
  asaas: {
    enabled: false,
    environment: "sandbox",
    baseUrl: "https://api-sandbox.asaas.com/v3",
    checkoutMode: "hosted",
    cardEnabled: true,
    splitEnabled: true,
    webhookPath: "/api/webhooks/asaas"
  },
  features: {
    venueDiscovery: true,
    mockReservations: true,
    partnerPortal: true,
    adminPortal: true,
    localPersistence: true,
    editableMockData: true,
    fullSubmenus: true,
    compactVenueDiscovery: true,
    partnerFacadeImages: true,
    venueSchedulePricing: true,
    groupLinkedReservations: true,
    standbyEvents: true,
    simulatedAutoPublish: true,
    simulatedPushLog: true,
    paidReservationCancellation: true,
    simulatedRefundFlow: true,
    simulatedCancellationVoucherFlow: true,
    voucherSingleUse: true,
    voucherPartnerLiability: true,
    partnerCancellationReason: true,
    tamoOnCancellationFlow: true,
    outsideDeadlineNoCompensation: true,
    exceptionalCancellationReview: true,
    voucherCompatibleAvailability: true,
    unifiedTamoOnProfile: true,
    googleAccountProfileSource: true,
    marketplaceProfileReadOnly: true,
    mobileFormZoomPrevention: true,
    mobileDialogViewportContainment: true,
    validationFreeDialogClose: true,
    compactPartnerKpis: true,
    transparentFinancialSplit: true,
    compactMobileAgendaActions: true,
    temporalFieldViewportFix: true,
    increasedDescriptionReadability: true,
    marketplaceLightTheme: true,
    persistentMarketplaceTheme: true,
    paymentProviderRouter: true,
    multiBankPixAdapters: true,
    directPartnerPix: true,
    automaticBankPixReconciliation: true,
    asaasCreditCardHostedCheckout: true,
    asaasCardSplitPrepared: true,
    providerWebhookNormalization: true,
    productionWrites: false
  }
});
